//-----------------------------------------------------------------------------
// TASKROSTER: TEAM INFO AND CHANGE TEAM
//-----------------------------------------------------------------------------
#define VN_IDD_TR_SHOWTEAMINFO 414200
#define VN_TR_SHOWTEAMINFO_LHS_LOGO_IDC 414201
#define VN_TR_SHOWTEAMINFO_LHS_TEAMNAME_IDC 414202
#define VN_TR_SHOWTEAMINFO_LHS_DESC_IDC 414203
#define VN_TR_SHOWTEAMINFO_LHS_ROLELIMITS_IDC 414204
#define VN_TR_SHOWTEAMINFO_LHS_PLAYERS_IDC 414205

#define VN_TR_SHOWTEAMINFO_RHS_IDC 414206
#define VN_TR_SHOWTEAMINFO_RHS_CHANGETEAM_LISTBOX_IDC 414207
#define VN_TR_SHOWTEAMINFO_RHS_CHANGETEAM_BUTTON_IDC 414208

#define VN_DISP_TR_SHOWTEAMINFO (uinamespace getvariable ["vn_tr_disp_showTeamInfo", DisplayNull])

#define VN_TR_SHOWTEAMINFO_RHS_CTRL (VN_DISP_TR_SHOWTEAMINFO displayCtrl VN_TR_SHOWTEAMINFO_RHS_IDC)
#define VN_TR_SHOWTEAMINFO_RHS_CHANGETEAM_LISTBOX_CTRL (VN_TR_SHOWTEAMINFO_RHS_CTRL controlsGroupCtrl VN_TR_SHOWTEAMINFO_RHS_CHANGETEAM_LISTBOX_IDC)
#define VN_TR_SHOWTEAMINFO_RHS_CHANGETEAM_BUTTON_CTRL (VN_TR_SHOWTEAMINFO_RHS_CTRL controlsGroupCtrl VN_TR_SHOWTEAMINFO_RHS_CHANGETEAM_BUTTON_IDC)

#define VN_TR_SHOWTEAMINFO_LHS_LOGO_CTRL (VN_DISP_TR_SHOWTEAMINFO displayCtrl VN_TR_SHOWTEAMINFO_LHS_LOGO_IDC)
#define VN_TR_SHOWTEAMINFO_LHS_TEAMNAME_CTRL (VN_DISP_TR_SHOWTEAMINFO displayCtrl VN_TR_SHOWTEAMINFO_LHS_TEAMNAME_IDC)
#define VN_TR_SHOWTEAMINFO_LHS_DESC_CTRL (VN_DISP_TR_SHOWTEAMINFO displayCtrl VN_TR_SHOWTEAMINFO_LHS_DESC_IDC)
#define VN_TR_SHOWTEAMINFO_LHS_ROLELIMITS_CTRL (VN_DISP_TR_SHOWTEAMINFO displayCtrl VN_TR_SHOWTEAMINFO_LHS_ROLELIMITS_IDC)
#define VN_TR_SHOWTEAMINFO_LHS_PLAYERS_CTRL (VN_DISP_TR_SHOWTEAMINFO displayCtrl VN_TR_SHOWTEAMINFO_LHS_PLAYERS_IDC)

