//-----------------------------------------------------------------------------
// TASKROSTER: PLAYER INFO + ROLES
//-----------------------------------------------------------------------------

// MAIN DISPLAY
#define VN_IDD_TR_SHOWPLAYERINFO 414098
#define VN_DISP_TR_SHOWPLAYERINFO (uinamespace getvariable ["vn_tr_disp_showPlayerInfo", DisplayNull])

// RIGHT HAND SIDE
// RIGHT HAND SIDE MAIN DISPLAY CONTROL
#define VN_TR_PLAYERINFO_RHS_IDC 414097
#define VN_TR_PLAYERINFO_RHS_CTRL (VN_DISP_TR_SHOWPLAYERINFO displayCtrl VN_TR_PLAYERINFO_RHS_IDC)

// RIGHT HAND SIDE ELEMENTS
#define VN_TR_PLAYERINFO_ROLES_IDC 414156
#define VN_TR_PLAYERINFO_ROLES_CTRL (VN_TR_PLAYERINFO_RHS_CTRL controlsGroupCtrl VN_TR_PLAYERINFO_ROLES_IDC)

// LEFT HAND SIDE
// LEFT HAND SIDE MAIN DISPLAY CTRL
#define VN_TR_PLAYERINFO_LHS_IDC 414099
#define VN_TR_PLAYERINFO_LHS_CTRL (VN_DISP_TR_SHOWPLAYERINFO displayCtrl VN_TR_PLAYERINFO_LHS_IDC)

// LEFT HAND SIDE ELEMENTS
#define PLAYERINFO_STATS_ROWY(IDX) (4 + IDX)

#define VN_TR_PLAYERINFO_NAME_IDC 414102
#define VN_TR_PLAYERINFO_SNUM_IDC 414103
#define VN_TR_PLAYERINFO_UID_IDC 414152
#define VN_TR_PLAYERINFO_RANK_IDC 414104
#define VN_TR_PLAYERINFO_POINTS_IDC 414107
#define VN_TR_PLAYERINFO_PROGR_IDC 414108
#define VN_TR_PLAYERINFO_KILLS_IDC 414153
#define VN_TR_PLAYERINFO_DEATHS_IDC 414154
#define VN_TR_PLAYERINFO_REWARD_TEXT_IDC 414109
#define VN_TR_PLAYERINFO_MEDAL_RIBBON_IDC 414150

#define VN_TR_PLAYERINFO_NAME_CTRL (VN_DISP_TR_SHOWPLAYERINFO displayCtrl VN_TR_PLAYERINFO_NAME_IDC)
#define VN_TR_PLAYERINFO_SNUM_CTRL (VN_DISP_TR_SHOWPLAYERINFO displayCtrl VN_TR_PLAYERINFO_SNUM_IDC)
#define VN_TR_PLAYERINFO_UID_CTRL (VN_DISP_TR_SHOWPLAYERINFO displayCtrl VN_TR_PLAYERINFO_UID_IDC)
#define VN_TR_PLAYERINFO_RANK_CTRL (VN_DISP_TR_SHOWPLAYERINFO displayCtrl VN_TR_PLAYERINFO_RANK_IDC)
#define VN_TR_PLAYERINFO_POINTS_CTRL (VN_DISP_TR_SHOWPLAYERINFO displayCtrl VN_TR_PLAYERINFO_POINTS_IDC)
#define VN_TR_PLAYERINFO_PROGR_CTRL (VN_DISP_TR_SHOWPLAYERINFO displayCtrl VN_TR_PLAYERINFO_PROGR_IDC)
#define VN_TR_PLAYERINFO_KILLS_CTRL (VN_DISP_TR_SHOWPLAYERINFO displayCtrl VN_TR_PLAYERINFO_KILLS_IDC)
#define VN_TR_PLAYERINFO_DEATHS_CTRL (VN_DISP_TR_SHOWPLAYERINFO displayCtrl VN_TR_PLAYERINFO_DEATHS_IDC)
#define VN_TR_PLAYERINFO_REWARD_TEXT_CTRL (VN_DISP_TR_SHOWPLAYERINFO displayCtrl VN_TR_PLAYERINFO_REWARD_TEXT_IDC)
#define VN_TR_PLAYERINFO_MEDAL_RIBBON_CTRL (VN_DISP_TR_SHOWPLAYERINFO displayCtrl VN_TR_PLAYERINFO_MEDAL_RIBBON_IDC)

// avoid creating 35 different ribbon controls... use some light macro magic.
#define GET_BY_ID_VN_TR_PLAYERINFO_RIBBON_IDC(IDX) (414115 + IDX)
#define GET_BY_ID_VN_TR_PLAYERINFO_RIBBON_CTRL(IDX) VN_DISP_TR_SHOWPLAYERINFO displayCtrl (414115 + IDX)
