#define VN_IDD_TR_TASKROSTER 45010
#define VN_DISP_TR_TASKROSTER (uinamespace getvariable ["vn_tr_disp_taskRoster_Main", DisplayNull])

#define VN_TR_BLANKSHEET_RHS_IDC 428000

#define VN_TR_NEWBIEHELP_BTN_IDC 428001
#define VN_TR_TEAMTEXT_BTN_IDC 428002
#define VN_TR_CURRTEAMTEXT_BTN_IDC 428003
#define VN_TR_MEDALSTEXT_BTN_IDC 428004
#define VN_TR_CHANGELOG_BTN_IDC 428005
#define VN_TR_CURRTASKSTEXT_BTN_IDC 428006
#define VN_TR_TASK_REQ_IDC 428007

#define VN_TR_BLANKSHEET_RHS_CTRL (VN_DISP_TR_TASKROSTER displayCtrl VN_TR_BLANKSHEET_RHS_IDC)

#define VN_TR_NEWBIEHELP_BTN_CTRL (VN_DISP_TR_TASKROSTER displayCtrl VN_TR_NEWBIEHELP_BTN_IDC)
#define VN_TR_TEAMTEXT_BTN_CTRL (VN_DISP_TR_TASKROSTER displayCtrl VN_TR_TEAMTEXT_BTN_IDC)
#define VN_TR_CURRTEAMTEXT_BTN_CTRL (VN_DISP_TR_TASKROSTER displayCtrl VN_TR_CURRTEAMTEXT_BTN_IDC)
#define VN_TR_MEDALSTEXT_BTN_CTRL (VN_DISP_TR_TASKROSTER displayCtrl VN_TR_MEDALSTEXT_BTN_IDC)
#define VN_TR_CHANGELOG_BTN_CTRL (VN_DISP_TR_TASKROSTER displayCtrl VN_TR_CHANGELOG_BTN_IDC)
#define VN_TR_CURRTASKSTEXT_BTN_CTRL (VN_DISP_TR_TASKROSTER displayCtrl VN_TR_CURRTASKSTEXT_BTN_IDC)
#define VN_TR_TASK_REQ_CTRL (VN_DISP_TR_TASKROSTER displayCtrl VN_TR_TASK_REQ_IDC)
